baseURL = "https://lukagiorgadze.com/"
languageCode = "en-us"
title = "Luka Giorgadze"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowToc = true
  env = "production"

[menu]
  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[pagination]
  pagerSize = 10